### PR TITLE
fix(bom): Fix generated pom.xml to omit invalid lombok declaration

### PR DESCRIPTION
**Pull request by Aloren**
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa

Currently all published `pom.xml` contain:
```
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version/>
      <scope>provided</scope>
    </dependency>
```
which is considered invalid by Maven and thus all transitive dependencies of such artifacts are omitted.

### CODE REVIEW

**Comment by marchello2000** [comment]
@Aloren thanks for the change. It looks good. There are some travis issues but I can merge these when travis ci resumes building.

In the meantime, can you please change other repos as well:

- [x] orca
- [x] kayenta
- [ ] clouddriver
- [ ] igor
- [ ] front50
- [ ] gate
- [ ] echo
- [ ] fiat

**Comment by Aloren** [comment]
changed commit message as requested by @spinnakerbot

**Comment by Aloren** [comment]
@marchello2000 i will also create prs to `spinnaker-gradle-project` and related projects to bump nebula plugins, so that `nebula-publishing-plugin` version override in all `spinnaker` projects could be removed

**Comment by Aloren** [comment]
clouddriver: https://github.com/spinnaker/clouddriver/pull/3847
igor: https://github.com/spinnaker/igor/pull/473
front50: https://github.com/spinnaker/front50/pull/552
gate: https://github.com/spinnaker/gate/pull/848
echo: https://github.com/spinnaker/echo/pull/596
fiat: https://github.com/spinnaker/fiat/pull/437

**Comment by Aloren** [comment]
Updates required in `gradle-netflixoss-project-plugin`:
https://github.com/nebula-plugins/gradle-netflixoss-project-plugin/pull/53

**Comment by marchello2000** [comment]
Thanks @Aloren ! Should I wait for you to update spinnaker-gradle-project then? because or merge these PRs?

**Comment by Aloren** [comment]
@marchello2000 this can be done separately I think.

**Pull request merged**
