### PR TITLE
chore(aws): Bump aws sdk

### PR DESCRIPTION
**Pull request by iandelahorne**
Bump AWS SDK to 1.11.1009

Fixes spinnaker/spinnaker#6417

### CODE REVIEW

**Comment by iandelahorne** [comment]
It's unclear to me how to test this locally as someone not 100% familiar with developing in the project. I've built this and run the `publishSpinnakerPublicationToMavenLocal` and `publishToMavenLocal` - but when I build clouddriver in the directory next to it with `clouddriver-web:installDist` it still pulls in 1.11.934 as it's dependency.

Do I need to publish to my own Maven repository to be able to test this?

**Comment by iandelahorne** [comment]
I've verified that this fixes spinnaker/spinnaker#6417.

**Review by zachsmith1 — APPROVED** [review]
LGTM

**Comment by zachsmith1** [comment]
cc: @pdk27

**Comment by zachsmith1** [comment]
cc: @allisaurus

**Review by allisaurus — APPROVED** [review]
LGTM

**Pull request merged**
