### PR TITLE
feat(stats): Add whitelist of cloud providers, as suggested by LF …

### PR DESCRIPTION
**Pull request by ttomsu**
…legal eagles.

@demobox @bdmorgan FYI

@duftler Did I get them all?

### CODE REVIEW

**Comment by ttomsu** [comment]
List obtained by looking through classes in Clouddriver that implement `CloudProvider` and grabbing their ID. Skipped `alicloud` for now since they're still working on it. Skipped `titus` because it's Netflix-only AFAIK.

**Comment by duftler** [comment]
huaweicloud also seems to be in progress: https://github.com/spinnaker/rosco/pull/466

The list looks right to me, best as I can tell from doing the same thing you did.

**Comment by demobox** [comment]
I'm wondering how we could easily be alerted if this list is no longer up-to-date?

**Comment by ttomsu** [comment]
Perhaps a Stackdriver log-based metric if an excessive number of UNKNOWNS (in any enum field) starts occurring.

**Pull request merged**
