### PR TITLE
feat(secrets/secrets-manager): Add AWS Secrets Manager secret engine

### PR DESCRIPTION
**Pull request by mayitbeegh**

### CODE REVIEW

**Comment by mayitbeegh** [comment]
Just realized that cache isn't doing anything. Maybe I'll add a working one later.

**Comment by fieldju** [comment]
@mayitbeegh would be great if you could make a PR to 
- https://www.spinnaker.io/reference/halyard/secrets/#supported-secret-engines <- add the new engine
- https://www.spinnaker.io/reference/halyard/secrets/s3-secrets/ <- make a new page with the relevant portions of https://github.com/Nike-Inc/cerberus#first-secrets

**Comment by fieldju** [comment]
@mayitbeegh here is where you can make those suggested edits: https://github.com/spinnaker/spinnaker.github.io/tree/master/reference/halyard/secrets

**Comment by akshayabd** [comment]
@mayitbeegh Hey Sean - there is an AWS SIG meeting tomorrow and we would love to see a demo of this if possible. Is that something you'd be interested in doing?

**Comment by mayitbeegh** [comment]
@akshayabd  I'm interested. I'm working with @fieldju to support more use cases. Hopefully we can demo them tomorrow.

**Comment by akshayabd** [comment]
@mayitbeegh Awesome! People would love to see this! The SIG meeting is tomorrow morning at 9:30 am PST, meeting link: https://meet.google.com/yfp-ekod-sxj - looking forward to seeing this amazing demo! Even if you can't demo just coming and chatting briefly about the work would be great!

**Comment by mayitbeegh** [comment]
Will be there!

**Pull request merged**
