### PR TITLE
Upgrade okhttp 4.x

### PR DESCRIPTION
**Pull request by droustchev-pd**
This is motivated by https://github.com/square/okhttp/issues/6738 and is based on the official upgrade instructions: https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/

Any guidance on additional tests/changes desired would be appreciated, since this is my first time contributing to this project.

### CODE REVIEW

**Comment by jasonmcintosh** [comment]
SO the kicker is... once this is done, all the OTHER Projects would likely need some work.  E.g. this is the shared lib used by clouddriver & orca & echo & gate & etc. :) That said, probably NEEDS to be done.

**Comment by dbyron-sf** [comment]
When I do a
```
./gradlew kork-web:dependencies
```
before and with this PR I see some potentially interesting diffs.

before:
```
+--- com.squareup.okhttp:okhttp -> 2.7.5
|    \--- com.squareup.okio:okio:1.6.0 -> 1.17.2
```
after:
```
+--- com.squareup.okhttp:okhttp -> 2.7.5
|    \--- com.squareup.okio:okio:1.6.0 -> 2.8.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 -> 1.5.32 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0 -> 1.5.32
```
Since there's still lots of code out there that uses `com.squareup.okhttp:okhttp`, is this safe?

**Comment by dbyron-sf** [comment]
Plus also in gate I see:
```
$ ./gradlew :gate-proxy:compileKotlin

> Task :gate-proxy:compileKotlin FAILED
e: /Users/dbyron/src/spinnaker/gate/gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt: (123, 88): Using 'url(): HttpUrl' is an error. moved to val
e: /Users/dbyron/src/spinnaker/gate/gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt: (138, 29): Using 'parse(String): MediaType?' is an error. moved to extension function
e: /Users/dbyron/src/spinnaker/gate/gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt: (148, 29): Using 'code(): Int' is an error. moved to val
e: /Users/dbyron/src/spinnaker/gate/gate-proxy/src/main/kotlin/com/netflix/spinnaker/gate/controllers/ProxyController.kt: (150, 31): Using 'body(): ResponseBody?' is an error. moved to val

FAILURE: Build failed with an exception.
```
which isn't the end of the world if we have a fix.  Would you mind creating a PR in gate that fixes this?  Then it's available to cherry-pick when things start to break.  Do you know what other repos need fixing?

**Comment by dbyron-sf** [comment]
Yeah, it's a bit of a pain without a monorepo.  I do it locally via something like:
```
./gradlew -Pversion=9.9.9-SNAPSHOT publishToMavenLocal
```
and then hand-edit `korkVersion` in the gradle.properties of each consuming microservice.  Do any of the other repos need changes?  Also still curious about the large version bumps I mentioned above.

**Comment by dbyron-sf** [comment]
Thanks for doing all of that.  A few notes:
* adding `checks.disable=true` to ~/.testcontainers.properties disables the disk space check.
* Besides docker, I don't know about any other dependencies, at least not for igor nor front50.  Did anything specific come up.
* https://github.com/spinnaker/kayenta is a bit of a special case since it doesn't depend on kork directly.  The way to test kayenta is to do a similar publishMavenLocal dance with orca and then hand-edit orcaVersion in kayenta's gradle.properties.

I need to stare at those retrofit links...

**Comment by dbyron-sf** [comment]
keel is a bit orphaned these days.  It would be great to fix the failures, but I'd rather not block this change waiting for that to happen.  I'm a little surprised about the front50 tests, but I wonder if that's something specific to your local environment.  The fact that the code and tests at least compile feels pretty good to me.

If you don't mind I'd like to wait a bit before merging this so I have some more time to exercise it locally.  I'm not exactly sure when it's going to happen...something like a week or two iI suspect.  Is that OK?

**Comment by dbyron-sf** [comment]
For the record, I don't actually see a change the version of kotlin.  In the "before":
```
com.squareup.okio:okio:1.6.0 -> 1.17.2
```
doesn't bring kotlin in, but the kotlin that's there is:
```
org.jetbrains.kotlin:kotlin-stdlib:1.5.32
org.jetbrains.kotlin:kotlin-stdlib-common:1.5.32
```
which is the same as the after:
```
+--- com.squareup.okhttp:okhttp -> 2.7.5
|    \--- com.squareup.okio:okio:1.6.0 -> 2.8.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 -> 1.5.32 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0 -> 1.5.32
```

**Comment by dbyron-sf** [comment]
And yes, https://github.com/square/okio/blob/master/CHANGELOG.md#version-200-rc1 does say explicitly:
```
Okio 2 is a major release that upgrades the library's implementation language from Java to Kotlin.

Okio 2.x is binary-compatible with Okio 1.x and does not change any behavior. Classes and .jar files compiled against 1.x can be used with 2.x without recompiling.

Okio 2.x is .java source compatible with Okio 1.x in all but one corner case. In Okio 1.x Buffer would throw an unchecked IllegalStateException when attempting to read more bytes than available. Okio 2.x now throws a checked EOFException in this case. This is now consistent with the behavior of its BufferedSource interface. Java callers that don't already catch IOException will now need to.
```

**Comment by dbyron-sf** [comment]
@mergifyio update

**Comment by dbyron-sf** [comment]
As I was testing this out, I came across a few cleanups.  There are enough that it's a little painful making individual comments.  Here are the diffs.  OK if I push, assuming I have permission?
```
    refactor(plugins): small cleanups
    
    - use toMediaType instead of toMediaTypeOrNull hard-coded media types,
    - replace deprecated RequestBody.create with toRequestBody extension method

diff --git a/kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/http/OkHttpRemoteExtensionTransport.kt b/kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/http/OkHttpRemoteExtensionTransport.kt
index a9f53999..703557ad 100644
--- a/kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/http/OkHttpRemoteExtensionTransport.kt
+++ b/kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/http/OkHttpRemoteExtensionTransport.kt
@@ -30,10 +30,10 @@ import com.netflix.spinnaker.security.AuthenticatedRequest
 import okhttp3.Headers
 import okhttp3.HttpUrl
 import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
+import okhttp3.MediaType.Companion.toMediaType
 import okhttp3.OkHttpClient
 import okhttp3.Request
-import okhttp3.RequestBody
+import okhttp3.RequestBody.Companion.toRequestBody
 
 /**
  * An HTTP [RemoteExtensionTransport], OkHttp for the client.
@@ -56,10 +56,7 @@ class OkHttpRemoteExtensionTransport(
         .url(url)
         .headers(buildHeaders(httpConfig.headers.invokeHeaders))
         .post(
-          RequestBody.create(
-            ("application/json").toMediaTypeOrNull(),
-            objectMapper.writeValueAsString(remoteExtensionPayload)
-          )
+          objectMapper.writeValueAsString(remoteExtensionPayload).toRequestBody(("application/json").toMediaType())
         )
         .build()
 
@@ -77,10 +74,7 @@ class OkHttpRemoteExtensionTransport(
         .url(url)
         .headers(buildHeaders(httpConfig.headers.writeHeaders))
         .post(
-          RequestBody.create(
-            ("application/json").toMediaTypeOrNull(),
-            objectMapper.writeValueAsString(remoteExtensionPayload)
-          )
+            objectMapper.writeValueAsString(remoteExtensionPayload).toRequestBody(("application/json").toMediaType())
         )
         .build()
 
diff --git a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/OkHttpRemoteExtensionTransportTest.kt b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/OkHttpRemoteExtensionTransportTest.kt
index 4f4fae71..97be6c87 100644
--- a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/OkHttpRemoteExtensionTransportTest.kt
+++ b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/remote/extension/transport/OkHttpRemoteExtensionTransportTest.kt
@@ -10,11 +10,11 @@ import dev.minutest.junit.JUnit5Minutests
 import dev.minutest.rootContext
 import io.mockk.every
 import io.mockk.mockk
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
+import okhttp3.MediaType.Companion.toMediaType
 import okhttp3.OkHttpClient
 import okhttp3.Protocol
 import okhttp3.Response
-import okhttp3.ResponseBody
+import okhttp3.ResponseBody.Companion.toResponseBody
 import strikt.api.expectThat
 import strikt.assertions.isA
 
@@ -31,7 +31,7 @@ class OkHttpRemoteExtensionTransportTest : JUnit5Minutests {
         .code(200)
         .message("OK")
         .header("Content-Type", "application/json")
-        .body(ResponseBody.create(("application/json").toMediaTypeOrNull(), "{\"type\": \"readResponse\", \"foo\": \"bar\"}"))
+        .body(("{\"type\": \"readResponse\", \"foo\": \"bar\"}").toResponseBody(("application/json").toMediaType()))
         .build()
 
       every { client.newCall(any()).execute() } returns response
@@ -47,7 +47,7 @@ class OkHttpRemoteExtensionTransportTest : JUnit5Minutests {
         .code(201)
         .message("OK")
         .header("Content-Type", "application/json")
-        .body(ResponseBody.create(("application/json").toMediaTypeOrNull(), "{\"type\": \"writeResponse\", \"foo\": \"bar\"}"))
+        .body(("{\"type\": \"writeResponse\", \"foo\": \"bar\"}").toResponseBody(("application/json").toMediaType()))
         .build()
 
       every { client.newCall(any()).execute() } returns response
diff --git a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt
index 4fb34017..2407fa22 100644
--- a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt
+++ b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt
@@ -23,11 +23,11 @@ import dev.minutest.rootContext
 import io.mockk.every
 import io.mockk.mockk
 import okhttp3.Call
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
+import okhttp3.MediaType.Companion.toMediaType
 import okhttp3.OkHttpClient
 import okhttp3.Protocol
 import okhttp3.Response
-import okhttp3.ResponseBody
+import okhttp3.ResponseBody.Companion.toResponseBody
 import strikt.api.expectThat
 import strikt.api.expectThrows
 import strikt.assertions.containsKey
@@ -49,7 +49,7 @@ class Ok3HttpClientTest : JUnit5Minutests {
         .code(200)
         .message("OK")
         .header("Content-Type", "plain/text")
-        .body(ResponseBody.create(("plain/text").toMediaTypeOrNull(), "hi"))
+        .body(("hi").toResponseBody(("plain/text").toMediaType()))
         .build()
 
       every { okHttpClient.newCall(any()) } returns call
diff --git a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3ResponseTest.kt b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3ResponseTest.kt
index deeea093..9bd4e458 100644
--- a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3ResponseTest.kt
+++ b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3ResponseTest.kt
@@ -21,10 +21,10 @@ import dev.minutest.junit.JUnit5Minutests
 import dev.minutest.rootContext
 import io.mockk.mockk
 import java.io.IOException
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
+import okhttp3.MediaType.Companion.toMediaType
 import okhttp3.Protocol
 import okhttp3.Response
-import okhttp3.ResponseBody
+import okhttp3.ResponseBody.Companion.toResponseBody
 import strikt.api.expectThat
 import strikt.assertions.isFalse
 import strikt.assertions.isTrue
@@ -67,7 +67,7 @@ internal class Ok3ResponseTest : JUnit5Minutests {
       .message("OK")
       .protocol(Protocol.HTTP_1_1)
       .header("Content-Type", "plain/text")
-      .body(ResponseBody.create(("plain/text").toMediaTypeOrNull(), "test"))
+      .body(("test").toResponseBody(("plain/text").toMediaType()))
       .build()
   }
 }
diff --git a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt
index 7636ca05..c35bf366 100644
--- a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt
+++ b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt
@@ -21,10 +21,10 @@ import io.mockk.every
 import io.mockk.mockk
 import java.net.URL
 import okhttp3.Call
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
+import okhttp3.MediaType.Companion.toMediaType
 import okhttp3.OkHttpClient
 import okhttp3.Response
-import okhttp3.ResponseBody
+import okhttp3.ResponseBody.Companion.toResponseBody
 import strikt.api.expect
 import strikt.api.expectThat
 import strikt.assertions.isEqualTo
@@ -41,7 +41,7 @@ class Front50FileDownloaderTest : JUnit5Minutests {
     test("files are downloaded to a temp directory") {
       every { response.isSuccessful } returns true
       every { response.code } returns 200
-      every { response.body } returns ResponseBody.create(("application/zip").toMediaTypeOrNull(), "oh hi")
+      every { response.body } returns ("oh hi").toResponseBody(("application/zip").toMediaType())
 
       expectThat(subject.downloadFile(URL("http://front50.com/myplugin.zip"))) {
         get { toFile().readText() }.isEqualTo("oh hi")
diff --git a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt
index 09564915..5beff9a3 100644
--- a/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt
+++ b/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt
@@ -26,8 +26,8 @@ import dev.minutest.junit.JUnit5Minutests
 import dev.minutest.rootContext
 import io.mockk.every
 import io.mockk.mockk
-import okhttp3.MediaType.Companion.toMediaTypeOrNull
-import okhttp3.ResponseBody
+import okhttp3.MediaType.Companion.toMediaType
+import okhttp3.ResponseBody.Companion.toResponseBody
 import retrofit2.Call
 import retrofit2.Response
 import strikt.api.expectThat
@@ -61,7 +61,7 @@ class Front50PluginInfoReleaseSourceTest : JUnit5Minutests {
 
       val call: Call<PinnedVersions> = mockk(relaxed = true)
       every { front50Service.pinVersions(eq("orca-v000"), eq("orca"), eq("us-west-2"), any()) } returns call
-      every { call.execute() } returns Response.error(500, ResponseBody.create(("application/json").toMediaTypeOrNull(), "{}"))
+      every { call.execute() } returns Response.error(500, ("{}").toResponseBody(("application/json").toMediaType()))
 
       subject.processReleases(releases)
 ```

**Comment by dbyron-sf** [comment]
ping @droustchev-pd.  Would love to get this in.

**Comment by dbyron-sf** [comment]
@mergifyio update

**Comment by dbyron-sf** [comment]
@mergifyio update

**Comment by dbyron-sf** [comment]
@mergifyio update

**Review by dbyron-sf — APPROVED** [review]

**Comment by dbyron-sf** [comment]
Thanks for sticking with this @droustchev-pd !  Tests are passing here, so I think we're good to go.

**Pull request merged**
