### PR TITLE
feat(web): Add optional Zipkin integration to RawOkHttpClientFactory

### PR DESCRIPTION
**Pull request by robzienert**
Doing the bare minimum for OSS here; getting Zipkin wired up into okhttp, but not configuring Sleuth. I suspect it's a slim chance that Zipkin is going to be utilized outside of Netflix, so I figured I would spare the effort of wiring that up for OSS.

Does this seem reasonable? Sleuth can always be added later for everyone else if there's demand.

### CODE REVIEW

**Comment by jonsie** [comment]
I think this looks more or less correct from an OkHttp3 client instrumentation perspective.  However, decorating the HttpTracing object with tags, server URL, sample rate, etc - I'm not sure if we get that for free from Sleuth/SBN-tracing or if we need to do that ourselves?

**Comment by robzienert** [comment]
The bean is annotated as `@ConditionalOnMissingBean`, I was planning that we would wire that up in our own stuff and pull stuff into OSS if it makes sense.

**Review by jonsie — APPROVED** [review]
Oh right.  Yeah I think this should be good to merge then.

**Comment by celiawa** [comment]
Hi @robzienert , could I know is there any guide on how to config  Zipkin integration?

**Pull request merged**
