### PR TITLE
Upgrade to Swagger2 (as part of springfox)

### PR DESCRIPTION
**Pull request by ajordens**
- Supports generation of a static API site via an integration with swagger2markup (http://springfox.github.io/springfox/docs/snapshot/#configuring-springfox-staticdocs)

### CODE REVIEW

**Comment by ajordens** [comment]
- No need to bundle the swagger-ui assets
- Swagger2 > Swagger
- io.springfox > com.mangofactory:swaggermvc

**Comment by duftler** [comment]
Looks like this breaks front50/rosco/rush as they are using swagger annotations that no longer resolve.

**Comment by ajordens** [comment]
Yes, I'll need to push through updates for anything that was using the old
annotations.

I guess I'm the new world any updates to dependencies take effect
immediately?

I'll get those other packages updated right away.

**Comment by duftler** [comment]
Thanks!

**Pull request merged**
