### PR TITLE
feature(web): Support more AuthenticatedRequest propagation

### PR DESCRIPTION
**Pull request by jvz**
This adds integration with Reactive Streams via Reactor and WebClient to propagating the current AuthenticatedRequest. This also extracts common logic for wrapping functions to do so into AuthenticatedRequestDecorator.

### CODE REVIEW

**Comment by dbyron-sf** [comment]
This is very exciting!  I have a couple of questions:
* Could you tell me some places where you're planning to use AuthenticatedRequestDecorator, or where AuthenticatedRequestConfiguration comes into play?  I'm curious where we'll start to propagate this info where we're not now.
* I took a peek at https://logging.apache.org/log4j/2.x/manual/thread-context.html to see how `ThreadContext.getContext()` differs from `MDC.getCopyOfContextMap()` but didn't see anything obvious besides being the "new way."  Are there any specific benefits to it, or differences that you know of?

Thanks much @jvz !

**Comment by dbyron-sf** [comment]
@mergifyio update

**Comment by jvz** [comment]
I used the Log4j api instead of SLF4J due to the same reasons I've suggested we switch to Log4j: more expansive API, maintained by more than one guy, and so forth

**Comment by jvz** [comment]
Let's just say I prefer to use dependencies where the maintainer doesn't disappear for years at a time

**Comment by dbyron-sf** [comment]
Fair enough...any details on what gaps in propagating the auth info this'll fill?

**Comment by jvz** [comment]
Well, for one, I'm not submitting code that uses dead dependencies, so jot that down lol

**Comment by jvz** [comment]
Plus of course I'm going to preference projects I'm a part of and know are still viable.

**Comment by jvz** [comment]
Or I can link to the usual page: https://logging.apache.org/log4j/2.x/manual/index.html

**Review by dbyron-sf — APPROVED** [review]

**Pull request merged**
