### PR TITLE
feat(core): add SpinnakerRetrofitErrorHandler

### PR DESCRIPTION
**Pull request by dbyron0**
Moved from clouddriver.  See https://github.com/spinnaker/clouddriver/pull/4325 + https://github.com/spinnaker/spinnaker/issues/5473.

### CODE REVIEW

**Review by robzienert — CHANGES_REQUESTED** [review]
This functionality should be added to `kork-retrofit`, not `kork-exceptions`.

**Comment by dbyron0** [comment]
> This functionality should be added to `kork-retrofit`, not `kork-exceptions`.

All of it, or only [SpinnakerRetrofitErrorHandler](https://github.com/spinnaker/kork/pull/821/files#diff-fc40665f8b24ab9d0d1e9a1eec2b28a74d5a69876b2827e58c90ef68acdd2f62) ?

**Comment by dbyron0** [comment]
OK, they all use retrofit...so moving them all.

**Comment by dbyron0** [comment]
> This functionality should be added to `kork-retrofit`, not `kork-exceptions`.

Done @robzienert

**Review by robzienert — APPROVED** [review]
Lovely.

**Comment by dbyron0** [comment]
Thanks much @robzienert !

**Pull request merged**
