### PR TITLE
bump springboot to 2.2.7

### PR DESCRIPTION
**Pull request by nimakaviani**
this fixes https://github.com/spinnaker/keel/issues/1409

/cc @luispollo

### CODE REVIEW

**Comment by luispollo** [comment]
@cfieber as part of the SpringBoot stuff you've been working on, have you had any issues with upgrading to later versions? We'd like to bump up the version slightly here, but this got me wondering if there's anything blocking us from upgrading to the next major.

**Comment by luispollo** [comment]
Ah. Spoke too soon. Found the PR where we had previously had to revert the exact same upgrade, @nimakaviani: https://github.com/spinnaker/kork/pull/665

@robfletcher would have more context.

**Comment by nimakaviani** [comment]
hmmm interesting. would be good to know how we can move forward and resolve the conflict with internal metrics.

**Comment by cfieber** [comment]
@luispollo I feel like its worth a try again to see if this is in a happy place for us, a lot has changed since the previous attempt got rolled back.

I'd suggest applying this locally and seeing if everything starts up fine running our internal wrapper

**Comment by luispollo** [comment]
> I'd suggest applying this locally and seeing if everything starts up fine running our internal wrapper

Thanks @cfieber, will do. I think my concern is that this affects all services, not just keel, but I can try with a couple.

**Comment by nimakaviani** [comment]
@luispollo did you by any chance get to try this version bump to see how things work?

**Comment by robzienert** [comment]
Ping.

**Comment by luispollo** [comment]
Sorry I missed the ping @robzienert and @nimakaviani. Will give this a try next week, so reopening this to track, and linking it to https://github.com/spinnaker/keel/issues/1409 which is the one I was keeping an eye on.

**Comment by luispollo** [comment]
OK... I gave this a shot today. Things were looking good until I tried our orca wrapper. It failed to start with this exception:
```
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.springframework.boot.actuate.autoconfigure.metrics.export.atlas.AtlasProperties; not a subtype of implementation type class org.springframework.boot.actuate.autoconfigure.metrics.export.properties.PushRegistryProperties
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:254)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:328)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	... 65 common frames omitted
```

There was a change to the `AtlasProperties` class hierarchy per https://github.com/spring-projects/spring-boot/issues/20843, however this breaks this app for us. I was unable to determine whether this is actually a bug in Spring Boot itself (since all other monitoring system properties classes seem to still extend `PushRegistryProperties` in 2.2.7) or a version incompatibility with internal Netflix libraries that setup Spectator. I don't have more bandwidth to look at this at this time, but wanted to let you know what I found.

In any case, @nimakaviani, based on our last conversation in the SIG, it didn't sound like you were blocked by this anymore, right?

**Pull request closed without merging**
